# pytorch_lightning==2.0.1
# Contains best parameters determined in grid search
seed_everything: 0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: models.SMPModel
  init_args:
    encoder_name: resnet18
    n_channels: 40
    flatten_temporal_dimension: true
    pos_class_weight: 236 # (relative frequency in augmented 2018 and 2020 fires)^-1
    loss_function: Dice

do_train: true
do_predict: false
do_test: true