# pytorch_lightning==2.0.1
# Updated with best found hyperparameters
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.01
model:
  class_path: ConvLSTMLightning
  init_args:
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight:  236 # (relative frequency in augmented 2018 and 2020 fires)^-1
    loss_function: "Jaccard"
    img_height_width: [128, 128]
    kernel_size: [3, 3]
    num_layers: 1

do_train: true
do_test: true
do_predict: false